DROP TABLE IF EXISTS ext_display_energy;

CREATE EXTERNAL TABLE ext_display_energy(
	LMK_KEY string,
	ADDRESS1 string,
	ADDRESS2 string,
	ADDRESS3 string,
	POSTCODE string,
	BUILDING_REFERENCE_NUMBER string,
	CURRENT_OPERATIONAL_RATING string,
	YR1_OPERATIONAL_RATING string,
	YR2_OPERATIONAL_RATING string,
	OPERATIONAL_RATING_BAND string,
	ELECTRIC_CO2 string,
	HEATING_CO2 string,
	RENEWABLES_CO2 string,
	PROPERTY_TYPE string,
	INSPECTION_DATE string,
	LOCAL_AUTHORITY string,
	CONSTITUENCY string,
	COUNTY string,
	LODGEMENT_DATE string,
	MAIN_BENCHMARK string,
	MAIN_HEATING_FUEL string,
	OTHER_FUEL string,
	SPECIAL_ENERGY_USES string,
	RENEWABLE_SOURCES string,
	TOTAL_FLOOR_AREA string,
	ANNUAL_THERMAL_FUEL_USAGE string,
	TYPICAL_THERMAL_FUEL_USAGE string,
	ANNUAL_ELECTRICAL_FUEL_USAGE string,
	TYPICAL_ELECTRICAL_FUEL_USAGE string,
	RENEWABLES_FUEL_THERMAL string,
	RENEWABLES_ELECTRICAL string,
	YR1_ELECTRICITY_CO2 string,
	YR2_ELECTRICITY_CO2 string,
	YR1_HEATING_CO2 string,
	YR2_HEATING_CO2 string,
	YR1_RENEWABLES_CO2 string,
	YR2_RENEWABLES_CO2 string,
	AIRCON_PRESENT string,
	AIRCON_KW_RATING string,
	ESTIMATED_AIRCON_KW_RATING string,
	AC_INSPECTION_COMMISSIONED string,
	BUILDING_ENVIRONMENT string,
	BUILDING_CATEGORY string,
	ADDRESS string,
	LOCAL_AUTHORITY_LABEL string,
	CONSTITUENCY_LABEL string,
	CERTIFICATE_HASH string)
	 ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
	WITH SERDEPROPERTIES (
	   "separatorChar" = ',',
	   "quoteChar"     = '\"',
	   "escapeChar"    = '\\'
	)  
	STORED AS TEXTFILE
	LOCATION '/tmp/energy/';



